name: Publish package to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number to tag and release'
        type: string
      release_type:
        description: Type of release. patch or minor (major if breaking)
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    outputs:
      version: ${{ steps.bump.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm install
      - name: Git Config
        run: |
          git config --global user.email "hello@matteocollina.com"
          git config --global user.name "Matteo Collina"
      - name: Change version number and push
        id: bump
        run: |
          npm version ${{ inputs.version || inputs.release_type }} --git-tag-version=false
          VERSION=`jq -r ".version" package.json`
          echo "::debug::Bumped $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          git add -u
          git commit -m "Bumped v$VERSION"
          git push origin HEAD:main
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  releasenotes:
    runs-on: ubuntu-latest
    needs: release

    permissions:
      contents: write

    env:
      VERSION: ${{ needs.release.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: 'Install release-notes'
        run: npm i @matteo.collina/release-notes -g
      - name: 'Debug'
        run: echo "::debug::Creating release notes for $VERSION"
      - name: 'Create release notes'
        run: |
          NOTES=`release-notes -a ${{ secrets.GITHUB_TOKEN }} -t v$VERSION -r test-publish -o mcollina`
          echo "# Released version $VERSION :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "url: $NOTES" >> $GITHUB_STEP_SUMMARY
